### ISSUE TITLE
Remove dependency on unused ARC algorithm from hashicorp/golang-lru

### ISSUE THREAD

**Issue by AkihiroSuda** [ipfs/boxo#366]
`arc_cache.go` seems modified to avoid hitting the patent (https://github.com/ipfs/go-ipfs-blockstore/pull/20) of ARC algorithm, but I was confused as the code comments still state that it uses the ARC algorithm.

https://github.com/ipfs/go-ipfs-blockstore/blob/03acccfc7eae2b977b3ec49663b6e23b6a1bdf9e/arc_cache.go#L16-L29

Could you add code comments to clarify the patent status of this file?

**Comment by AkihiroSuda** [comment]
It would be also nice if go-ipfs-blockstore could avoid importing `hashicorp/golang-lru` which still contains ARC codes (https://github.com/hashicorp/golang-lru/issues/73) , or switch to an ARC-free fork.

https://github.com/ipfs/go-ipfs-blockstore/blob/8aad3d8b2d942b8cf8fd90ee9b6dc958935bfe05/go.mod#L4

**Comment by AkihiroSuda** [comment]
@Stebalien could you take a look? 🙏

**Comment by AkihiroSuda** [comment]
@guseggert @Stebalien 

Would it be possible to replace  github.com/hashicorp/golang-lru with @ktock 's ARC-free fork?
https://github.com/ktock/golang-lru/commit/ec551be6f75c10a4f18e3c70a823d03420ee3d4f

We (the containerd project) are already using his fork: https://github.com/containerd/nerdctl/blob/9efa1234350bab9a5150fbb5b7f3655aa24f82e1/go.mod#L172-L173

**Comment by Stebalien** [comment]
I'm happy to accept a patch with the comment requested in the original issue, but I'd rather not switch to a random fork (especially when upstream is active as we're likely going to switch to their new generic version sooner rather than later).

Patents aren't like copyright. Has a lawyer told you you can't import that library? Patents are all about _using_ patented technologies.

**Comment by BigLep** [comment]
Given we haven't heard back more on this, it's not clear the priority of this right now.

**Comment by AkihiroSuda** [comment]
> patch

I'm not feeling that I'm the right person to submit this patch, as I don't have good understanding of the code and the patent.

I'd appreciate if we can get the patch from the maintainers or at least somebody who has better understanding than me.

> Has a lawyer told you you can't import that library?

No, importing the library is probably okay as long as it is not used, but it is slightly hard to attest that the patented code is not actually used, when it is imported.
( So, in our project we run `go tool nm | grep NewARC` in the CI: https://github.com/containerd/nerdctl/blob/v1.1.0/hack/verify-no-patent.sh )

**Comment by lidel** [comment]
It seems the problem was resolved in the upstream library – ARC code was moved to separate package:

- Release Notes: https://github.com/hashicorp/golang-lru/releases/tag/v2.0.3

So the remaining work here is to:
- [x]  switch boxo to hashicorp/golang-lru v2.0.3 or later
- [x] remove mentions of arccache and ARC, as we've switched to TwoQueueCache long time ago, but comments and names are still here

PR: https://github.com/ipfs/boxo/pull/367
